language: python
sudo: false
python:
  - "pypy3"
env:
  - RUN=one
  - RUN=two
  - RUN=three
install:
    - pip install -vr requirements.txt
# command to run tests, e.g. python setup.py test
script:
  - echo $TRAVIS_PYTHON_VERSION
  - python setup.py install
  - python --jit off `which supybot-test` test -v --plugins-dir=./build/lib*/supybot/plugins/ --no-network --disable-multiprocessing --exclude=./build/lib*/supybot/plugins/Scheduler --exclude=./build/lib*/supybot/plugins/Filter
notifications:
    email: false
matrix:
  fast_finish: true
